In [15]:
import numpy as np

In [186]:
# 3D array
print("3d array")
c=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print (c)

3d array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [4]:
np.empty((4,4), dtype=int)

array([[     0,      0,      0,      0],
       [     0,      0,      0,      0],
       [     0,      0,   2060,      0],
       [     0,    329,      0, 917833]])

In [5]:
a=np.arange(1,20)
print (a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [60]:
b=np.arange(2,20,2)
print(b)

[ 2  4  6  8 10 12 14 16 18]


In [63]:
b = b.reshape((3,3))
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [69]:
a=np.arange(1,51)
a=a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [71]:
a[0]

array([1, 2, 3, 4, 5])

In [72]:
a[3,4]

20

In [73]:
a[:,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [19]:
a=np.arange(1,19).reshape((6,3))
b=np.arange(20,38).reshape((6,3))
print(a)
print(b)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [80]:
a-b

array([[-19, -19, -19],
       [-19, -19, -19],
       [-19, -19, -19],
       [-19, -19, -19],
       [-19, -19, -19],
       [-19, -19, -19]])

In [84]:
a.max()

18

In [20]:
np.sum(b, axis=0)

array([165, 171, 177])

In [41]:
np.random.random(1)

array([0.60867185])

In [92]:
np.random.random((2,2))

array([[0.93002298, 0.56668824],
       [0.09174179, 0.95135394]])

In [146]:
np.random.randint(1, 10)

3

In [172]:
np.random.randint(1,10,(3,4,5))

array([[[5, 7, 2, 3, 8],
        [5, 1, 9, 9, 9],
        [5, 8, 5, 8, 6],
        [3, 4, 7, 4, 2]],

       [[7, 6, 1, 9, 7],
        [8, 6, 3, 5, 6],
        [7, 7, 5, 7, 4],
        [4, 7, 5, 2, 3]],

       [[3, 7, 8, 1, 2],
        [9, 8, 3, 6, 1],
        [7, 2, 8, 2, 8],
        [2, 2, 6, 1, 2]]])

In [173]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
np.random.choice(a)

2

In [190]:
s1='my name is anish'
s2='i am 20 years old' 

In [191]:
np.char.add(s1,s2)

array('my name is anishi am 20 years old', dtype='<U33')

In [192]:
np.char.split(s1)

array(list(['my', 'name', 'is', 'anish']), dtype=object)

In [201]:
np.char.replace(s1,'name','sirname')

array('my sirname is anish', dtype='<U19')

In [206]:
print(np.char.center('goodbye',80,'*'))

************************************goodbye*************************************
